// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  call_to_action: dynamic(() => import("./CallToAction")),
  cols_with_image_text: dynamic(() => import("./ColsWithImageText")),
  contact_us: dynamic(() => import("./ContactUs")),
  events_list: dynamic(() => import("./EventsList")),
  faq: dynamic(() => import("./Accordion")),
  features: dynamic(() => import("./Features")),
  free_txt: dynamic(() => import("./FreeTxt")),
  hero: dynamic(() => import("./Hero")),
  hight_lights: dynamic(() => import("./HightLights")),
  home_slider: dynamic(() => import("./SliderImages")),
  jobs_form: dynamic(() => import("./JobsForm")),
  jobs_list: dynamic(() => import("./JobsList")),
  latest_events: dynamic(() => import("./LatestEvents")),
  latest_jobs: dynamic(() => import("./LatestJobs")),
  latest_news: dynamic(() => import("./LatestNews")),
  latest_recipes: dynamic(() => import("./LatestRecipes")),
  navigation_item: dynamic(() => import("./NavigationItem")),
  news_list: dynamic(() => import("./NewsList")),
  newsletter: dynamic(() => import("./Newsletter")),
  promo_products: dynamic(() => import("./PromoProducts")),
  recipes_list: dynamic(() => import("./RecipesList")),
  search_result: dynamic(() => import("./SearchResult")),
  simple_cover: dynamic(() => import("./SimpleCover")),
  slice_double_col_with_picto: dynamic(() => import("./DoubleColWithPicto")),
  testimonials: dynamic(() => import("./Testimonials")),
  text_with_image: dynamic(() => import("./TextWithImage")),
  top_of_news: dynamic(() => import("./TopOfNews")),
  video: dynamic(() => import("./Video")),
};
